### PR TITLE
Add types and providers from crayfishx/puppet-rhsm

### LINKED ISSUE #87: Use types and providers for subscriptions and repositories
@crayfishx provides a puppet-rhsm module with a slightly different focus. We are currently using a mix of both modules, because we need to enable additional subscriptions (products on Satellite 6) through Puppet (not only by the use of an activation key or multiple activation keys).

My proposal is to combine both modules (both are Apache License 2.0). An option would be to import the types and providers (`rh_subscription`/`rh_repo`) from crayfishx/rhsm. Adding those would also allow us to get rid of some `exec` resources and maybe resource dependencies.

### PR DESCRIPTION
**Pull request by kallies**
#### Pull Request (PR) description
This PR introduces types and providers used in @crayfishx 's puppet-rhsm.

This is useful if you need to enable additional subscriptions (products on Satellite 6) through Puppet (not only by the use of an activation key or multiple activation keys).

#### This Pull Request (PR) fixes the following issues

Fixes #87

### CODE REVIEW

**Comment by kallies** [comment]
The first commit introduces almost 1:1 copies of the types and providers from @crayfishx 's rhsm module.

Open point:

* Fix rubocop issues

**Comment by kallies** [comment]
I could use some help with `self.instance` and the rubocop warning `Redundant curly braces around a hash parameter.` which causes the Puppet 6 test to fail.

**Comment by kallies** [comment]
Successfully tested in an environment with Satellite 6, EPEL subscription, EPEL repository with Puppet 5.5.10 on RHEL 7.

**Comment by kallies** [comment]
Successfully tested on RHEL 6.

**Comment by bastelfreak** [comment]
Thanks @kallies !

**Pull request merged**
