### PR TITLE
Noosestroke package params

### PR DESCRIPTION
**Pull request by noosestroke**
#### Pull Request (PR) description
Add package profile parameters to puppet-rhsm module

### CODE REVIEW

**Comment by kallies** [comment]
This PR refers to

1. https://github.com/candlepin/subscription-manager/pull/487/files and
1. https://github.com/candlepin/subscription-manager/pull/1966/files

Looks good to me.

**Comment by kallies** [comment]
In general I think about using a config hash for the `rhsm.conf` settings. So we would not need to specify them each time a new setting pops up.

**Comment by noosestroke** [comment]
> In general I think about using a config hash for the `rhsm.conf` settings. So we would not need to specify them each time a new setting pops up.

Good idea, but where should the hash be sourced from? The subscription-manager rhsm.conf(5) manpage ? Or the rpmnew file?

**Comment by kallies** [comment]
The hash should simple be a parameter which is evaluated to build the `rhsm.conf`. E.g.

```
  $rhsm_conf = {},
```

**Pull request closed without merging**
