### PR TITLE
release 0.3.0

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by igalic** [comment]
is there a reason why we didn't release this as 1.0.0?

**Comment by bastelfreak** [comment]
the last forge release was 0.2.0. I don't know enough about rhsm to determine if this is a stable and ready module.

**Comment by bbriggs** [comment]
I'm doing some manual acceptance testing on this today. Last night I was able to manage RHSM for an already-registered machine without issues. 

Test cases for today: 
 - Changing/managing channels and entitlements
 - Registering brand new machines

**Comment by bbriggs** [comment]
I've been doing testing with this in my site and it's working fine. I plan on deploying to prod for myself starting Monday. 

-- Briggs

**Comment by igalic** [comment]
@bbriggs in that case, it'd be cool if we could offictially bump this to v1.0.0

**Comment by bbriggs** [comment]
I'll cut that release later today :)

**Comment by bastelfreak** [comment]
we can't release until https://github.com/travis-ci/dpl/issues/487#issuecomment-236660825 is fixed.

**Pull request merged**
