### PR TITLE
Added confine rule on Fact

### PR DESCRIPTION
**Pull request by tux-o-matic**
Without this, any other node than Red Hat (could be Windows) with this module in its node classification would have the Puppet Ruby runtime attempting to execute this Fact.

### CODE REVIEW

**Comment by tux-o-matic** [comment]
@bastelfreak, any stand on the Rubocop test failing because of the format for https://github.com/bbatsov/ruby-style-guide#hash-literals ?

**Comment by bastelfreak** [comment]
You can fix this automatically by running:

```shell
bundle exec rubocop -c .rubocop.yml -D -S -a
```

**Comment by tux-o-matic** [comment]
Thanks for the tip @bastelfreak. 
Should be good to merge now.

**Comment by bastelfreak** [comment]
Thanks for the fix!

**Pull request merged**
