### PR TITLE
Read enabled repositories from inifile

### LINKED ISSUE #90: Read facts from /etc/yum.repos.d/redhat.repo instead of subscription-manager
As stated by @alexjfisher in #53 `subscription-manager` might lead to long puppet runs and - in case RHSM/Satellite 6 is down - might lead to issues when relying on the resulting facts:

If the Satellite server (or RHSM) is not accessible or sends http errorcodes.

1. Not accessible: Puppet runs are stale until `subscription-manager` times out (default timeout is 180s per http request and `subscription-manager repos --list-enabled` triggers ~7 requests)
2. Satellite/RHSM frontend answers with http errorcode: fact returns empty array -> if someone (like we do) evaluates this fact to enable repos, Puppet tries to enable all repos (again - not a big issue but def. not a nice behaviour). 

We were thinking about a caching mechanism which addresses these two issues.

Instead of calling `subscription-manager` or `yum` the file `/etc/yum.repos.d/redhat.repo` should be evaluated

 ".. or search for `enabled = 1` and all sections without `enabled`

This should also address both issues.

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: >=4
- Ruby: generic
- Distribution: RHEL
- Module version: 3.2.1-rc0/master

## How to reproduce (e.g Puppet code you use)

As described in README.md

## What are you seeing

Slow puppet runs (>10s for `subscription-manager`), issues when Satellite 6 is not available or - even worse - partially available.

### PR DESCRIPTION
**Pull request by kallies**
#### Pull Request (PR) description

Read enabled repositories from inifile.

`subscription-manager` is slow and `yum` causes locks, just read from `/etc/yum.repos.d/redhat.repo` file.

#### This Pull Request (PR) fixes the following issues

Fixes #90

### CODE REVIEW

**Comment by kallies** [comment]
rubocop checks fail for unmodified inifile (https://github.com/TwP/inifile)

**Comment by speer** [comment]
Why not using: `puppet/util/inifile`?

```
      repos = Array.[]
      repo_file = Puppet::Util::IniConfig::PhysicalFile.new('/etc/yum.repos.d/redhat.repo')
      repo_file.read
      repo_file.sections.each do |section|
        repos.push(section.name) if section['enabled'].nil? || section['enabled'].to_i == 1
      end
      { enabled_repo_ids: repos }
```

**Comment by kallies** [comment]
@speer this is something I was looking for, thanks!

**Comment by kallies** [comment]
Closing in favour of #95

**Pull request closed without merging**
